package com.paici.app.ui.camera

/**
 * ML Kit Image Labeling 返回英文标签对应的 IPA 音标。
 * Key 与 LabelToChineseMap 完全一致（小写英文）。
 * 找不到时调用方显示 "/ — /" 占位。
 */
val labelToPhonetic: Map<String, String> = mapOf(
    // 食物
    "apple"        to "/ˈæpəl/",
    "banana"       to "/bəˈnænə/",
    "orange"       to "/ˈɔːrɪndʒ/",
    "grape"        to "/ɡreɪp/",
    "strawberry"   to "/ˈstrɔːberi/",
    "watermelon"   to "/ˈwɔːtərmelən/",
    "lemon"        to "/ˈlemən/",
    "mango"        to "/ˈmæŋɡoʊ/",
    "peach"        to "/piːtʃ/",
    "pear"         to "/per/",
    "pizza"        to "/ˈpiːtsə/",
    "burger"       to "/ˈbɜːrɡər/",
    "hamburger"    to "/ˈhæmbɜːrɡər/",
    "sandwich"     to "/ˈsænwɪtʃ/",
    "bread"        to "/bred/",
    "cake"         to "/keɪk/",
    "cookie"       to "/ˈkʊki/",
    "coffee"       to "/ˈkɔːfi/",
    "tea"          to "/tiː/",
    "milk"         to "/mɪlk/",
    "juice"        to "/dʒuːs/",
    "rice"         to "/raɪs/",
    "noodle"       to "/ˈnuːdəl/",
    "soup"         to "/suːp/",
    "salad"        to "/ˈsæləd/",
    "egg"          to "/eɡ/",
    "cheese"       to "/tʃiːz/",
    "chocolate"    to "/ˈtʃɔːklət/",
    "ice cream"    to "/ˈaɪs kriːm/",
    "food"         to "/fuːd/",
    "fruit"        to "/fruːt/",
    "vegetable"    to "/ˈvedʒtəbəl/",
    "drink"        to "/drɪŋk/",
    "snack"        to "/snæk/",
    // 动物
    "dog"          to "/dɔːɡ/",
    "cat"          to "/kæt/",
    "bird"         to "/bɜːrd/",
    "fish"         to "/fɪʃ/",
    "horse"        to "/hɔːrs/",
    "elephant"     to "/ˈeləfənt/",
    "bear"         to "/ber/",
    "lion"         to "/ˈlaɪən/",
    "tiger"        to "/ˈtaɪɡər/",
    "rabbit"       to "/ˈræbɪt/",
    "cow"          to "/kaʊ/",
    "pig"          to "/pɪɡ/",
    "chicken"      to "/ˈtʃɪkɪn/",
    "duck"         to "/dʌk/",
    "snake"        to "/sneɪk/",
    "turtle"       to "/ˈtɜːrtəl/",
    "panda"        to "/ˈpændə/",
    "monkey"       to "/ˈmʌŋki/",
    "animal"       to "/ˈænɪməl/",
    "mammal"       to "/ˈmæməl/",
    "insect"       to "/ˈɪnsekt/",
    "butterfly"    to "/ˈbʌtərflaɪ/",
    // 家具 / 室内
    "chair"        to "/tʃer/",
    "table"        to "/ˈteɪbəl/",
    "sofa"         to "/ˈsoʊfə/",
    "bed"          to "/bed/",
    "desk"         to "/desk/",
    "shelf"        to "/ʃelf/",
    "door"         to "/dɔːr/",
    "window"       to "/ˈwɪndoʊ/",
    "lamp"         to "/læmp/",
    "clock"        to "/klɑːk/",
    "mirror"       to "/ˈmɪrər/",
    "carpet"       to "/ˈkɑːrpɪt/",
    "curtain"      to "/ˈkɜːrtən/",
    "pillow"       to "/ˈpɪloʊ/",
    "furniture"    to "/ˈfɜːrnɪtʃər/",
    // 电子产品
    "laptop"       to "/ˈlæptɑːp/",
    "phone"        to "/foʊn/",
    "mobile phone" to "/ˈmoʊbəl foʊn/",
    "smartphone"   to "/ˈsmɑːrtfoʊn/",
    "television"   to "/ˈtelɪvɪʒən/",
    "camera"       to "/ˈkæmərə/",
    "keyboard"     to "/ˈkiːbɔːrd/",
    "mouse"        to "/maʊs/",
    "headphones"   to "/ˈhedfoʊnz/",
    "tablet"       to "/ˈtæblɪt/",
    "computer"     to "/kəmˈpjuːtər/",
    "screen"       to "/skriːn/",
    "charger"      to "/ˈtʃɑːrdʒər/",
    "electronics"  to "/ɪˌlekˈtrɑːnɪks/",
    // 文具 / 办公
    "book"         to "/bʊk/",
    "pen"          to "/pen/",
    "pencil"       to "/ˈpensəl/",
    "paper"        to "/ˈpeɪpər/",
    "notebook"     to "/ˈnoʊtbʊk/",
    "ruler"        to "/ˈruːlər/",
    "scissors"     to "/ˈsɪzərz/",
    "envelope"     to "/ˈenvəloʊp/",
    // 餐具
    "cup"          to "/kʌp/",
    "mug"          to "/mʌɡ/",
    "bottle"       to "/ˈbɑːtəl/",
    "bowl"         to "/boʊl/",
    "plate"        to "/pleɪt/",
    "fork"         to "/fɔːrk/",
    "knife"        to "/naɪf/",
    "spoon"        to "/spuːn/",
    "chopsticks"   to "/ˈtʃɑːpstɪks/",
    "pot"          to "/pɑːt/",
    "pan"          to "/pæn/",
    // 衣物 / 配饰
    "shirt"        to "/ʃɜːrt/",
    "jacket"       to "/ˈdʒækɪt/",
    "coat"         to "/koʊt/",
    "dress"        to "/dres/",
    "pants"        to "/pænts/",
    "shoe"         to "/ʃuː/",
    "sneaker"      to "/ˈsniːkər/",
    "hat"          to "/hæt/",
    "glasses"      to "/ˈɡlæsɪz/",
    "bag"          to "/bæɡ/",
    "backpack"     to "/ˈbækpæk/",
    "umbrella"     to "/ʌmˈbrelə/",
    "watch"        to "/wɑːtʃ/",
    "ring"         to "/rɪŋ/",
    "glove"        to "/ɡlʌv/",
    "scarf"        to "/skɑːrf/",
    "clothing"     to "/ˈkloʊðɪŋ/",
    "fashion"      to "/ˈfæʃən/",
    // 交通
    "car"          to "/kɑːr/",
    "bicycle"      to "/ˈbaɪsɪkəl/",
    "bus"          to "/bʌs/",
    "train"        to "/treɪn/",
    "airplane"     to "/ˈerpleɪn/",
    "boat"         to "/boʊt/",
    "motorcycle"   to "/ˈmoʊtərsaɪkəl/",
    "truck"        to "/trʌk/",
    "vehicle"      to "/ˈviːɪkəl/",
    // 自然
    "tree"         to "/triː/",
    "flower"       to "/ˈflaʊər/",
    "leaf"         to "/liːf/",
    "grass"        to "/ɡræs/",
    "mountain"     to "/ˈmaʊntən/",
    "river"        to "/ˈrɪvər/",
    "sea"          to "/siː/",
    "sky"          to "/skaɪ/",
    "cloud"        to "/klaʊd/",
    "sun"          to "/sʌn/",
    "moon"         to "/muːn/",
    "star"         to "/stɑːr/",
    "rain"         to "/reɪn/",
    "snow"         to "/snoʊ/",
    "fire"         to "/ˈfaɪər/",
    "stone"        to "/stoʊn/",
    "rock"         to "/rɑːk/",
    "sand"         to "/sænd/",
    "plant"        to "/plænt/",
    "nature"       to "/ˈneɪtʃər/",
    "forest"       to "/ˈfɔːrɪst/",
    "beach"        to "/biːtʃ/",
    // 建筑 / 场所
    "building"     to "/ˈbɪldɪŋ/",
    "house"        to "/haʊs/",
    "room"         to "/ruːm/",
    "road"         to "/roʊd/",
    "bridge"       to "/brɪdʒ/",
    "park"         to "/pɑːrk/",
    "school"       to "/skuːl/",
    "hospital"     to "/ˈhɑːspɪtəl/",
    "store"        to "/stɔːr/",
    // 运动 / 娱乐
    "ball"         to "/bɔːl/",
    "toy"          to "/tɔɪ/",
    "game"         to "/ɡeɪm/",
    "music"        to "/ˈmjuːzɪk/",
    "art"          to "/ɑːrt/",
    "sport"        to "/spɔːrt/",
    // 人体
    "person"       to "/ˈpɜːrsən/",
    "hand"         to "/hænd/",
    "face"         to "/feɪs/",
    "eye"          to "/aɪ/",
    "hair"         to "/her/",
    "smile"        to "/smaɪl/",
    // 其他
    "money"        to "/ˈmʌni/",
    "key"          to "/kiː/",
    "gift"         to "/ɡɪft/",
    "map"          to "/mæp/",
    "flag"         to "/flæɡ/",
    "sign"         to "/saɪn/",
    "light"        to "/laɪt/",
    "color"        to "/ˈkʌlər/",
)
