package com.paici.app.ui.camera

/**
 * ML Kit Image Labeling 返回英文标签，此映射表提供对应中文释义。
 * Key 为小写英文（与 label.text.lowercase() 对应）。
 * 找不到时调用方显示"—"占位。
 */
val labelToChinese: Map<String, String> = mapOf(
    // 食物
    "apple" to "苹果",
    "banana" to "香蕉",
    "orange" to "橙子",
    "grape" to "葡萄",
    "strawberry" to "草莓",
    "watermelon" to "西瓜",
    "lemon" to "柠檬",
    "mango" to "芒果",
    "peach" to "桃子",
    "pear" to "梨",
    "pizza" to "披萨",
    "burger" to "汉堡",
    "hamburger" to "汉堡",
    "sandwich" to "三明治",
    "bread" to "面包",
    "cake" to "蛋糕",
    "cookie" to "饼干",
    "coffee" to "咖啡",
    "tea" to "茶",
    "milk" to "牛奶",
    "juice" to "果汁",
    "rice" to "米饭",
    "noodle" to "面条",
    "soup" to "汤",
    "salad" to "沙拉",
    "egg" to "鸡蛋",
    "cheese" to "奶酪",
    "chocolate" to "巧克力",
    "ice cream" to "冰淇淋",
    "food" to "食物",
    "fruit" to "水果",
    "vegetable" to "蔬菜",
    "drink" to "饮料",
    "snack" to "零食",
    // 动物
    "dog" to "狗",
    "cat" to "猫",
    "bird" to "鸟",
    "fish" to "鱼",
    "horse" to "马",
    "elephant" to "大象",
    "bear" to "熊",
    "lion" to "狮子",
    "tiger" to "老虎",
    "rabbit" to "兔子",
    "cow" to "牛",
    "pig" to "猪",
    "chicken" to "鸡",
    "duck" to "鸭子",
    "snake" to "蛇",
    "turtle" to "乌龟",
    "panda" to "熊猫",
    "monkey" to "猴子",
    "animal" to "动物",
    "mammal" to "哺乳动物",
    "insect" to "昆虫",
    "butterfly" to "蝴蝶",
    // 家具 / 室内
    "chair" to "椅子",
    "table" to "桌子",
    "sofa" to "沙发",
    "bed" to "床",
    "desk" to "书桌",
    "shelf" to "书架",
    "door" to "门",
    "window" to "窗户",
    "lamp" to "台灯",
    "clock" to "时钟",
    "mirror" to "镜子",
    "carpet" to "地毯",
    "curtain" to "窗帘",
    "pillow" to "枕头",
    "furniture" to "家具",
    // 电子产品
    "laptop" to "笔记本电脑",
    "phone" to "手机",
    "mobile phone" to "手机",
    "smartphone" to "智能手机",
    "television" to "电视",
    "camera" to "相机",
    "keyboard" to "键盘",
    "mouse" to "鼠标",
    "headphones" to "耳机",
    "tablet" to "平板电脑",
    "computer" to "电脑",
    "screen" to "屏幕",
    "charger" to "充电器",
    "electronics" to "电子产品",
    // 文具 / 办公
    "book" to "书",
    "pen" to "钢笔",
    "pencil" to "铅笔",
    "paper" to "纸",
    "notebook" to "笔记本",
    "ruler" to "尺子",
    "scissors" to "剪刀",
    "envelope" to "信封",
    // 餐具
    "cup" to "杯子",
    "mug" to "马克杯",
    "bottle" to "瓶子",
    "bowl" to "碗",
    "plate" to "盘子",
    "fork" to "叉子",
    "knife" to "刀",
    "spoon" to "勺子",
    "chopsticks" to "筷子",
    "pot" to "锅",
    "pan" to "平底锅",
    // 衣物 / 配饰
    "shirt" to "衬衫",
    "jacket" to "夹克",
    "coat" to "外套",
    "dress" to "裙子",
    "pants" to "裤子",
    "shoe" to "鞋",
    "sneaker" to "运动鞋",
    "hat" to "帽子",
    "glasses" to "眼镜",
    "bag" to "包",
    "backpack" to "背包",
    "umbrella" to "雨伞",
    "watch" to "手表",
    "ring" to "戒指",
    "glove" to "手套",
    "scarf" to "围巾",
    "clothing" to "服装",
    "fashion" to "时尚",
    // 交通
    "car" to "汽车",
    "bicycle" to "自行车",
    "bus" to "公共汽车",
    "train" to "火车",
    "airplane" to "飞机",
    "boat" to "船",
    "motorcycle" to "摩托车",
    "truck" to "卡车",
    "vehicle" to "车辆",
    // 自然
    "tree" to "树",
    "flower" to "花",
    "leaf" to "叶子",
    "grass" to "草",
    "mountain" to "山",
    "river" to "河流",
    "sea" to "海",
    "sky" to "天空",
    "cloud" to "云",
    "sun" to "太阳",
    "moon" to "月亮",
    "star" to "星星",
    "rain" to "雨",
    "snow" to "雪",
    "fire" to "火",
    "stone" to "石头",
    "rock" to "岩石",
    "sand" to "沙子",
    "plant" to "植物",
    "nature" to "自然",
    "forest" to "森林",
    "beach" to "海滩",
    // 建筑 / 场所
    "building" to "建筑",
    "house" to "房子",
    "room" to "房间",
    "road" to "道路",
    "bridge" to "桥",
    "park" to "公园",
    "school" to "学校",
    "hospital" to "医院",
    "store" to "商店",
    // 运动 / 娱乐
    "ball" to "球",
    "toy" to "玩具",
    "game" to "游戏",
    "music" to "音乐",
    "art" to "艺术",
    "sport" to "运动",
    // 人体
    "person" to "人",
    "hand" to "手",
    "face" to "脸",
    "eye" to "眼睛",
    "hair" to "头发",
    "smile" to "微笑",
    // 其他
    "money" to "钱",
    "key" to "钥匙",
    "gift" to "礼物",
    "map" to "地图",
    "flag" to "旗帜",
    "sign" to "标志",
    "light" to "灯光",
    "color" to "颜色",
)
